import './globals.css'
import { Inter } from 'next/font/google'
import NextLink from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header style={{ marginBottom: 16 }}>
					<ul>
						<li>
							<NextLink href="/">&rarr; Home</NextLink>
						</li>
						<li>
							<NextLink href="/example">&rarr; Example</NextLink>
						</li>
					</ul>
				</header>

				{children}
			</body>
		</html>
	)
}
